layout_spectrum: 0.1893657
typography_spectrum: 0.6996269
color:
  saturation: 0.4655283
  lightness: 0.5288339
  brandStrength: 0.544358
  rhythmicContrast: 0.2582744
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Nemanja
